openapi: 3.0.1

info:
  title: TextGenerationAPI
  description: |
      Text Generation API using Huggingface Transformers
  version: "0.1"
paths:
  /ping:
    get:
      tags:
      - Health Check
      responses:
        '200':
          description: get status of model server
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                example:
                  status: "Healthy"

  /predictions/text-generation:
    post:
      tags:
      - Inference
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text_inputs:
                  type: string
                  example: My name is Thomas and my main
                max_length:
                  type: integer
                  example: 20
                min_length:
                  type: integer
                  example: 10
                do_sample:
                  type: boolean
                  example: False
                early_stopping:
                  type: boolean
                  example: False
                num_beams:
                  type: integer
                  example: 1
                temperature:
                  type: number
                  example: 1.0
                top_k:
                  type: integer
                  example: 50
                top_p:
                  type: number
                  example: 1.0
                repetition_penalty:
                  type: number
                  example: 1.0
                length_penalty:
                  type: number
                  example: 1.0
                no_repeat_ngram_size:
                  type: integer
                  example: 0
                num_return_sequences:
                  type: integer
                  example: 1
              required:
                - text_inputs
              example:
                text_inputs: 인간처럼 생각하고, 행동하는 '지능'을 통해 인류가 이제까지 풀지 못했던
                temperature: 0.8
                max_length: 64
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: [
                 "인간처럼 생각하고, 행동하는 '지능'을 통해 인류가 이제까지 풀지 못했던 문제의 해답을 찾을 수 있을 것이다. 과학기술이 고도로 발달한 21세기를 살아갈 우리 아이들에게 가장 필요한 것은 사고력 훈련이다. 사고력 훈련을 통해, 세상"
                ] 
        '400':
          description: Bad Request
        '500':
          description: Server side error
tags:
- name: Inference